//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothek
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowingBookActivities
    {
        public int Id { get; set; }
        public Nullable<int> BorrowingBooksId { get; set; }
        public Nullable<int> TransactionTypeId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> DateOfBorrowing { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> DelayTime { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedByName { get; set; }
        public string Note { get; set; }
    
        public virtual BookTransactionType BookTransactionType { get; set; }
        public virtual BorrowingBooks BorrowingBooks { get; set; }
        public virtual Staves Staves { get; set; }
    }
}
