//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothek
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowingBooks
    {
        public int Id { get; set; }
        public System.DateTime IssueDate { get; set; }
        public int Period { get; set; }
        public System.DateTime ReturningDate { get; set; }
        public int NumberOfRentals { get; set; }
        public int BorrowingBookActivityId { get; set; }
        public int StudentId { get; set; }
        public int BookId { get; set; }
        public int StaffId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedByName { get; set; }
        public string Note { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual BorrowingBookActivities BorrowingBookActivities { get; set; }
        public virtual Staves Staves { get; set; }
        public virtual Students Students { get; set; }
    }
}
