//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothek
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowingBooks
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<System.DateTime> BorrowingDate { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<System.DateTime> ReturningDate { get; set; }
        public Nullable<int> DelayTime { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public Nullable<int> BorrowedFrom { get; set; }
        public Nullable<int> SubmittedAt { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Staffs Staffs { get; set; }
        public virtual Staffs Staffs1 { get; set; }
        public virtual Students Students { get; set; }
    }
}
