//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Countries()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int Id { get; set; }
        public string CountryName { get; set; }
        public string OfficialShortName { get; set; }
        public string OfficialFullName { get; set; }
        public string Nationality { get; set; }
        public string ContinentName { get; set; }
        public string ContinentCode { get; set; }
        public string ISO3166_2 { get; set; }
        public string ISO_3166_3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
    }
}
