//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliothek
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffRoles
    {
        public int StaffId { get; set; }
        public int RoleId { get; set; }
        public string Descripton { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Staves Staves { get; set; }
    }
}
